# Generated by Django 4.2.5 on 2023-09-17 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chor',
            name='participants',
            field=models.ManyToManyField(editable=False, through='user.UserChorRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
