
services:
  web:
    build: ./cm_app
    command: gunicorn -c /usr/src/cm_app/config/gunicorn/conf.py
    container_name: chormeister-web
    expose:
      - 8000
    env_file:
      - ./.envs/.env.psql
      - ./.envs/.env
    volumes:
      - ./cm_app:/usr/src/cm_app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "sh", "/usr/src/cm_app/bash/healthcheck.sh" ]
      start_period: 30s
      start_interval: 1s
      interval: 1s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:15-alpine
    container_name: chormeister-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - ./.envs/.env.psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 1s
  server:
    build: ./nginx
    container_name: chormeister-server
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
    name: chormeister-db-volume
  static_volume:
    name: chormeister-static-volume
  media_volume:
    name: chormeister-media-volume
