# version: '3.8'

services:
  web:
    build: ./cm_app
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./cm_app/:/usr/src/cm_app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.psql
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    # container_name: chormeister-psql
    ports:
      - 8006:5432
    volumes:
      - ./db_configs:/etc/postgresql/configs
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.psql
    # command: ["postgres", "-D", "/etc/postgresql/configs"]
    # command: ["postgres", "-c", "config_file=/etc/postgresql/configs/postgresql.conf"]

volumes:
  postgres_data:
