
services:
  web:
    build: ./cm_app
    command: gunicorn -c /usr/src/cm_app/config/gunicorn/conf.py
    container_name: test-chormeister-web
    expose:
      - 8000
    networks:
      - testing
    environment:
      - DJANGO_SECRET_KEY=somekey
      - CHORMEISTER_DOMAIN=chormeisters.com
      - CHORMEISTER_IP=someip
      - STATIC_ROOT=/home/app/web/staticfiles/
      - DATABASE=postgres
      - DJANGO_SUPERUSER_USERNAME=someuser
      - DJANGO_SUPERUSER_PASSWORD=somepassword
      - DJANGO_SUPERUSER_EMAIL=some@example.com
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpassword
      - POSTGRES_DB=psqldb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./cm_app:/usr/src/cm_app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    restart: "no"
    healthcheck:
      test: [ "CMD", "sh", "/usr/src/cm_app/bash/healthcheck.sh" ]
      start_period: 30s
      start_interval: 1s
      interval: 1s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:15-alpine
    container_name: test-chormeister-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: "no"
    networks:
      - testing
    environment:
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=psqlpassword
      - POSTGRES_DB=psqldb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 1s
  server:
    build: ./nginx
    container_name: test-chormeister-server
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    networks:
      - testing
    restart: "no"
    depends_on:
      web:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
    name: test-chormeister-db-volume
  static_volume:
    name: test-chormeister-static-volume
  media_volume:
    name: test-chormeister-media-volume

networks:
  testing: 
