
services:
  web:
    build: ./cm_app
    command: gunicorn -c /usr/src/cm_app/config/gunicorn/conf.py
    expose:
      - 8000
    env_file:
      - ./.env.psql
      - ./.env.dev
    volumes:
      - ./dumps:/dumps
      - static_volume:/home/app/web/staticfiles
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - ./.env.psql
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
