# Generated by Django 4.2.1 on 2023-06-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chor', '0002_alter_chor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=models.SET('deleted'), related_name='created_chors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chor',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
