# Generated by Django 4.2.1 on 2023-06-05 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('chor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chor',
            name='participants',
            field=models.ManyToManyField(editable=False, through='user.UserChorRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
