# Generated by Django 4.2.1 on 2023-05-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chor', '0002_songperformance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='songperformance',
            options={'ordering': ['-dtofperformance']},
        ),
        migrations.AlterModelOptions(
            name='songpropertyname',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='songperformance',
            old_name='datetime',
            new_name='dtofperformance',
        ),
    ]
