# Generated by Django 4.2.1 on 2023-06-05 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chor', '0003_alter_chor_participants'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='chor.chor')),
            ],
        ),
    ]
