# Generated by Django 4.2.1 on 2023-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchorrole',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
