# Generated by Django 4.2.1 on 2023-06-03 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chor', '0002_alter_chor_name'),
        ('user', '0002_userchorrole_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchorrole',
            unique_together={('chor', 'user')},
        ),
    ]
