name: Deploy to the server

on:
  push:
    branches: [ main ]
    
jobs:
  check-if-builds:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker compose -f docker-compose.test.yml up -d

  shh-to-server-and-pull:
    runs-on: ubuntu-latest
    needs: check-if-builds

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
          cd chormeisterweb/Chormeister
          git pull origin main
          git status
          bash ./bash/rebuild.sh -d
          